server:
  error:
    include-stacktrace: on_param

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/aerocompany?createDatabaseIfNotExist=true
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:aerocompany
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
